server.port=2050

spring.application.name=@name@

info.app.name=@name@
info.app.version=@version@
info.app.description=@description@

url.service.database=http://localhost:2060/gda/service-database/


##Facturacion Publico
path.file.qr=/mnt/gda/DesarrolloGDA/documentosTimbrao/imgs/qr.png

path.file.logo.azteca=/mnt/gda/DesarrolloGDA/documentosTimbrao/imgs/AZTECA.png
path.files.pdf.azteca=/mnt/gda/DesarrolloGDA/documentosTimbrao/pdf/Azteca/pdf/

path.file.logo.jenner=/mnt/gda/DesarrolloGDA/documentosTimbrao/imgs/JENNER.png
path.files.pdf.jenner=/mnt/gda/DesarrolloGDA/documentosTimbrao/pdf/Jenner/pdf/

path.file.logo.liacsa=/mnt/gda/DesarrolloGDA/documentosTimbrao/imgs/Liacsa.jpg
path.files.pdf.liacsa=/mnt/gda/DesarrolloGDA/documentosTimbrao/pdf/Liacsa/pdf/

path.file.logo.olab=/mnt/gda/DesarrolloGDA/documentosTimbrao/imgs/OLAB.png
path.files.pdf.olab=/mnt/gda/DesarrolloGDA/documentosTimbrao/pdf/Olab/pdf/

path.file.logo.swisslab=/mnt/gda/DesarrolloGDA/documentosTimbrao/imgs/SWISSLAB.png
path.files.pdf.swisslab=/mnt/gda/DesarrolloGDA/documentosTimbrao/pdf/Swisslab/pdf/

path.file.logo.familylabsnorte=/mnt/gda/DesarrolloGDA/documentosTimbrao/imgs/FamilyLabsNorte.png
path.files.pdf.familylabsnorte=/mnt/gda/DesarrolloGDA/documentosTimbrao/pdf/FamilyLabsNorte/pdf/

path.file.logo.asesoressur=/mnt/gda/DesarrolloGDA/documentosTimbrao/imgs/AsesoresSur.png
path.files.pdf.asesoressur=/mnt/gda/DesarrolloGDA/documentosTimbrao/pdf/AsesoresSur/pdf/

path.file.logo.exakta.laboratorio=/mnt/gda/DesarrolloGDA/documentosTimbrao/imgs/EXAKTA-LABORATORIO.jpg
path.file.logo.exakta.imagen=/mnt/gda/DesarrolloGDA/documentosTimbrao/imgs/EXAKTA-IMAGEN.jpg
path.file.logo.exakta.quimica=/mnt/gda/DesarrolloGDA/documentosTimbrao/imgs/EXAKTA-BIOANALISIS.jpg
path.files.pdf.exakta=/mnt/gda/DesarrolloGDA/documentosTimbrao/pdf/Exakta/pdf/


##Facturacion 
path.file.ordenes.pdf.olab=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Olab/XMLTMP/PDF/
path.file.ordenes.pdf.azteca=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Azteca/XMLTMP/PDF/
path.file.ordenes.pdf.swisslab=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Swisslab/XMLTMP/PDF/
path.file.ordenes.pdf.prado=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Jenner/Prado/XMLTMP/PDF/
path.file.ordenes.pdf.lean=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Jenner/Lean/XMLTMP/PDF/
path.file.ordenes.pdf.jenner=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Jenner/
path.file.ordenes.pdf.familylabsnorte=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_FamilyLabsNorte/XMLTMP/PDF/
path.file.ordenes.pdf.asesoressur=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_AsesoresSur/XMLTMP/PDF/

path.file.ordenes.logo.azteca=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Azteca/XMLTMP/IMGS/AZTECA.png
path.file.ordenes.qr.azteca=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Azteca/XMLTMP/IMGS/qr.png

path.file.ordenes.logo.jenner=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Jenner/XMLTMP/IMGS/JENNER.png

path.file.ordenes.logo.olab=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Olab/XMLTMP/IMGS/OLAB.png
path.file.ordenes.qr.olab=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Olab/XMLTMP/IMGS/qr.png

path.file.ordenes.logo.swisslab=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Swisslab/XMLTMP/IMGS/SWISSLAB.png
path.file.ordenes.qr.swisslab=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Swisslab/XMLTMP/IMGS/qr.png

path.file.ordenes.logo.familylabsnorte=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_FamilyLabsNorte/XMLTMP/IMGS/FamilyLabsNorte.png

path.file.ordenes.logo.asesoressur=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_AsesoresSur/XMLTMP/IMGS/AsesoresSur.png

path.file.ordenes.logo.liacsa=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Swisslab/XMLTMP/IMGS/Liacsa.jpg


##Cadena Original TFD
path.file.cadena.original.tfd=/mnt/gda/DesarrolloGDA/documentosTimbrao/Cadena Original/TFD/cadenaoriginal_TFD_1_1.xslt

##Logger Configuration 
logging.file.path=/mnt/gda/DesarrolloGDA/logsApisFacturacion/servicePdf/logs
logging.file.name=${logging.file.path}/${spring.application.name}.log
logging.pattern.console= %d{yyyy-dd_dd HH:mm:ss} [%thread] %-5level %logger{36} %L - %msg%n
logging.pattern.file= %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} %L- %msg%n
logging.logback.rollingpolicy.file-name-pattern=${logging.file.path}/${spring.application.name}.%d{dd-MM-yyyy}.%i.gz
logging.logback.rollingpolicy.total-size-cap=3GB
logging.logback.rollingpolicy.max-history=8