server.port=2020

spring.application.name=@name@

info.app.name=@name@
info.app.version=@version@
info.app.description=@description@

cfdi.version=3.3
cfdi.version.4=4.0

#Retencion
cfdi.retencion.monto=0.06

##Cadena Original##
path.file.cadena.original=/mnt/gda/DesarrolloGDA/documentosTimbrao/Cadena Original/V3_3/CadenaOriginalV3.3.xslt
path.file.cadena.original.4=/mnt/gda/DesarrolloGDA/documentosTimbrao/Cadena Original/V4_0/cadenaoriginal.xslt

## OLAB ##
path.file.key.olab=/mnt/gda/DesarrolloGDA/documentosTimbrao/Certificado Olab/CSD_ADM_ECD741021QA5_20200923_092557.key
path.file.cer.olab=/mnt/gda/DesarrolloGDA/documentosTimbrao/Certificado Olab/00001000000505145362.cer
password.cer.olab=Q1U1ZCFI
rfc.marca.olab=ECD741021QA5
razon.social.olab=ESTUDIOS CLINICOS DR TJ ORIARD SA DE CV
numero.certificado.olab=00001000000505145362

## AZTECA ##
path.file.key.azteca=/mnt/gda/DesarrolloGDA/documentosTimbrao/Certificado Azteca/CSD_CORP_LQC920131M20_20191204_120110.key
path.file.cer.azteca=/mnt/gda/DesarrolloGDA/documentosTimbrao/Certificado Azteca/00001000000502350617.cer
password.cer.azteca=Q1LQCU12020#
rfc.marca.azteca=LQC920131M20
razon.social.azteca=LABORATORIO QUIMICO CLINICO AZTECA SAPI DE CV
numero.certificado.azteca=00001000000502350617

## PRADO ##
path.file.key.prado=/mnt/gda/DesarrolloGDA/documentosTimbrao/Certificado Jenner/Prado/CSD_MATRIZ_LCP061017PA9_20200529_140416.key
path.file.cer.prado=/mnt/gda/DesarrolloGDA/documentosTimbrao/Certificado Jenner/Prado/00001000000504077431.cer
password.cer.prado=GDA2020lcp
rfc.marca.prado=LCP061017PA9
razon.social.prado=LABORATORIO CLINICO DEL PRADO SA DE CV
numero.certificado.prado=00001000000504077431

## LEAN ##
path.file.key.lean=/mnt/gda/DesarrolloGDA/documentosTimbrao/Certificado Jenner/Lean/CSD_LABORATORIO_CLINICO_LEAN_SA_DE_CV_LCL050622DD9_20160530_103102.key
path.file.cer.lean=/mnt/gda/DesarrolloGDA/documentosTimbrao/Certificado Jenner/Lean/00001000000402641452.cer
password.cer.lean=gacr490129
rfc.marca.lean=LCL050622DD9
razon.social.lean=LABORATORIO CLINICO LEAN S.A. DE C.V.
numero.certificado.lean=00001000000402641452

## SWISSLAB ##
path.file.key.swisslab=/mnt/gda/DesarrolloGDA/documentosTimbrao/Certificado Swisslab/CSD_Matriz_SWI1201268J8_20210517_191237.key
path.file.cer.swisslab=/mnt/gda/DesarrolloGDA/documentosTimbrao/Certificado Swisslab/00001000000507423256.cer
password.cer.swisslab=GDA2021swi
rfc.marca.swisslab=SWI1201268J8
razon.social.swisslab=SWISSLAB S.A. de C.V.
numero.certificado.swisslab=00001000000507423256


list.sucursal.jenner.prado=117,118,126,127,128,129,130,132,134,138,139,140,141,142,143,196,198,199,200
list.sucursal.jenner.lean=115,116,119,120,121,122,123,124,125,131,133,135,136,137,177,146,197

url.service.database=http://localhost:2060/gda/service-database/





#URLS Facturas
facturas.documentos.servidor=http://10.3.0.7:9085/
facturas.download.url=/mnt/gda/apache-tomcat/webapps/ROOT/
facturas.download.url.xml=/XML/
facturas.download.url.pdf=/XMLTMP/PDF/
facturas.dowload.prefijo.azteca=FacturacionElectronica_AZ
facturas.dowload.prefijo.swisslab=FacturacionElectronica_AS
facturas.dowload.prefijo.olab=FacturacionElectronica_A
facturas.dowload.prefijo.lean=FacturacionElectronica_AJL
facturas.dowload.prefijo.prado=FacturacionElectronica_AJP

facturas.dowload.folder.azteca=FacturasElectronicas_Azteca
facturas.dowload.folder.swisslab=FacturasElectronicas_Swisslab
facturas.dowload.folder.olab=FacturasElectronicas_Olab
facturas.dowload.folder.lean=FacturasElectronicas_Jenner/Lean
facturas.dowload.folder.prado=FacturasElectronicas_Jenner/Prado



#Complemento de Pagos
complemento.pagos.xml.default.cveprod=84111506
complemento.pagos.xml.default.cantidad=1
complemento.pagos.xml.default.cveunidad=ACT
complemento.pagos.xml.default.pago=Pago
complemento.pagos.xml.default.version=1.0





###Logger Configuration 
logging.level.org.springframework.jdbc.core=TRACE
logging.file.path=/mnt/gda/DesarrolloGDA/logsApisFacturacion/serviceCfdi/logs
logging.file.name=${logging.file.path}/${spring.application.name}.log
logging.pattern.console= %d{yyyy-dd_dd HH:mm:ss} [%thread] %-5level %logger{36} %L - %msg%n
logging.pattern.file= %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} %L- %msg%n
logging.logback.rollingpolicy.file-name-pattern=${logging.file.path}/${spring.application.name}.%d{dd-MM-yyyy}.%i.gz
logging.logback.rollingpolicy.total-size-cap=3GB
logging.logback.rollingpolicy.max-history=8
